routes/web.php
<?php

use App\Http\Controllers\PermissionController;
use App\Http\Controllers\RoleController;
use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return redirect('login');
});

Auth::routes();

Route::get('/home', [App\Http\Controllers\HomeController::class, 'index'])->name('home');

Route::group([
    "middleware" => "auth"
], function(){
    Route::resource('roles', RoleController::class);
    Route::resource('permission', PermissionController::class);
});

app/Http/Controllers/RoleController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use Spatie\Permission\Models\Role;

class RoleController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $data['roles'] = Role::latest()->get();
        return view('module.role.index', $data);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        //
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        Role::create([
            'name' => $request->name
        ]);

        return redirect()->back();
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        //
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        //
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        Role::find($id)->delete();
        return back();
    }
}

resources/views/module/role/index.blade.php
<x-base-app-layout>
    <div class="container-fluid">
        <div class="row">
            <div class="col-12">
                <h1 class="display-5 fw-bold">Management Roles</h1>
                <p>Halaman untuk management roles</p>
            </div>
            <div class="col-12 mb-2 mb-md-4">
                <form action="{{ route('roles.store') }}" method="post">
                    @csrf
                    <div class="form-group">
                        <div class="input-group">
                            <input type="text" class="form-control" name="name" placeholder="Input New roles">
                            <div class="input-group-append">
                                <button type="submit" class="btn btn-primary" id="basic-addon2">Submit</button>
                            </div>
                        </div>
                    </div>
                </form>
            </div>
            <div class="col-12 p-0">
                <div class="table-responsive">
                    <table class="table" id="tableroles">
                        <thead>
                            <tr>
                                <th>No</th>
                                <th>Name</th>
                                <th>Action</th>
                            </tr>
                        </thead>
                        <tbody>
                            @foreach ($roles as $p => $permi)
                            <tr>
                                <td>{{ $p+1 }}</td>
                                <td>{{ $permi->name }}</td>
                                <td>
                                    <span class="btn btn-primary" data-toggle="modal" data-target="#exampleModal">Edit</span>
                                    <form action="{{ route('roles.destroy', $permi->id) }}" method="POST" class="d-inline ms-2">
                                        @csrf 
                                        @method('delete')
                                        <button type="submit" class="btn btn-primary" onclick="if( !confirm('Do you want to continue?') ) return false;">Delete</button>
                                    </form>
                                </td>
                            </tr>
                            @endforeach
                        </tbody>
                    </table>
                </div>
            </div>
            <div class="modal fade" id="exampleModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel"
                aria-hidden="true">
                <div class="modal-dialog" role="document">
                    <div class="modal-content">
                        <div class="modal-header">
                            <h5 class="modal-title" id="exampleModalLabel">roles Update</h5>
                            <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                                <span aria-hidden="true">&times;</span>
                            </button>
                        </div>
                        <div class="modal-body">
                            <form method="post" id="formUpdate">
                                @csrf
                                @method('put')
                                <div class="form-group">
                                    <div class="input-group">
                                        <input type="text" class="form-control" placeholder="Input New roles">
                                        <div class="input-group-append">
                                            <button type="submit" class="btn btn-primary"
                                                id="basic-addon2">Update</button>
                                        </div>
                                    </div>
                                </div>
                            </form>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <x-slot name="script">
        <script>
            $("#tableroles").DataTable();
        </script>
    </x-slot>
</x-base-app-layout>