routes/web.php
<?php

use App\Http\Controllers\PermissionController;
use App\Http\Controllers\RoleController;
use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return redirect('login');
});

Auth::routes();

Route::get('/home', [App\Http\Controllers\HomeController::class, 'index'])->name('home');

Route::group([
    "middleware" => "auth"
], function(){
    Route::resource('roles', RoleController::class);
    Route::resource('permission', PermissionController::class);
});

resources/views/layouts/admin/sidebar/main-nav-sidebar-component.blade.php
<ul class="nav nav-primary">

    <x-single-list-sidebar-component link="" activate="">
        <x-slot name="icon"><i class="la flaticon-layers-1"></i></x-slot>
        <x-slot name="text">Dashboard</x-slot>
    </x-single-list-sidebar-component>

    <li class="nav-section">
        <span class="sidebar-mini-icon">
            <i class="fa fa-ellipsis-h"></i>
        </span>
        <h4 class="text-section">Components</h4>
    </li>

    {{-- ini contoh sidebar dropdown --}}
    <x-multiple-list-sidebar-component idSidebar="chart">
        <x-slot name="icon"><i class="la flaticon-interface-1"></i></x-slot>
        <x-slot name="text">User</x-slot>
        {{-- ini contoh untuk sub sidebarnya, link dan activate silahkan ganti sesuai penggunaan --}}
        <x-sublist-multiple-sidebar-component link="/index.html" activate="sublist">
            <x-slot name="text">list</x-slot>
        </x-sublist-multiple-sidebar-component>
    </x-multiple-list-sidebar-component>

    {{-- ini contoh single sidebar --}}
    <x-single-list-sidebar-component link="/index.html" activate="index">
        <x-slot name="icon"><i class="la flaticon-interface-1"></i></x-slot>
        <x-slot name="text">User</x-slot>
        <x-slot name="notif">Hallo</x-slot>
    </x-single-list-sidebar-component>

    <li class="nav-section">
        <span class="sidebar-mini-icon">
            <i class="fa fa-ellipsis-h"></i>
        </span>
        <h4 class="text-section">User & Roles</h4>
    </li>

    {{-- ini contoh single sidebar --}}
    <x-single-list-sidebar-component link="{{ route('roles.index') }}" activate="roles">
        <x-slot name="icon"><i class="la flaticon-user-5"></i></x-slot>
        <x-slot name="text">Roles</x-slot>
    </x-single-list-sidebar-component>
    <x-single-list-sidebar-component link="{{ route('permission.index') }}" activate="permission">
        <x-slot name="icon"><i class="la flaticon-lock-1"></i></x-slot>
        <x-slot name="text">Permission</x-slot>
    </x-single-list-sidebar-component>


</ul>

resources/views/layouts/admin/sidebar/multiple-list-sidebar-component.blade.php
<li class="nav-item">
        <a data-toggle="collapse" href="{{ "#".$idSidebar }}">
            {{-- <i class="far fa-chart-bar"></i> --}}
            {{ $icon }}
            <p>{{ $text }}</p>
            <span class="caret"></span>
        </a>
        <div class="collapse" id="{{ $idSidebar }}">
            <ul class="nav nav-collapse">
                {{ $slot }}
                {{-- <x-sublist-multiple-sidebar-component></x-sublist-multiple-sidebar-component>
                <x-sublist-multiple-sidebar-component></x-sublist-multiple-sidebar-component> --}}
            </ul>
        </div>
    </li>

resources/views/layouts/admin/sidebar/nav-section-sidebar-component.blade.php
<li class="nav-section">
    <span class="sidebar-mini-icon">
        <i class="fa fa-ellipsis-h"></i>
    </span>
    <h4 class="text-section">Components</h4>
</li>

resources/views/layouts/admin/sidebar/single-list-sidebar-component.blade.php
<li class="nav-item @if (Request::segment(1) == $activate) 
        active 
    @endif">
    <a href="{{ $link }}">
        {{ $icon }}
        <p>{{ $text }}</p>
        @isset($notif)
        <span class="badge badge-count">{{ $notif }}</span>
        @endisset
    </a>
</li>

resources/views/layouts/admin/sidebar/sublist-multiple-sidebar-component.blade.php
<li @if(Request::segment(2) == $activate)
    class="active"
@endif>
    <a href="{{ $link }}">
        <span class="sub-item">{{ $text }}</span>
    </a>
</li>

resources/views/layouts/admin/sidebar/user-sidebar-component.blade.php
<div class="user">
    <div class="avatar-sm float-left mr-2">
        <img src="../assets/img/profile.jpg" alt="..." class="avatar-img rounded-circle">
    </div>
    <div class="info">
        <a data-toggle="collapse" href="#collapseExample" aria-expanded="true">
            <span>
                Syahrul
                <span class="user-level">Administrator</span>
                <span class="caret"></span>
            </span>
        </a>
        <div class="clearfix"></div>

        <div class="collapse in" id="collapseExample">
            <ul class="nav">
                <li>
                    <a href="#profile">
                        <span class="link-collapse">My Profile</span>
                    </a>
                </li>
                <li>
                    <a href="#edit">
                        <span class="link-collapse">Edit Profile</span>
                    </a>
                </li>
                <li>
                    <a href="#settings">
                        <span class="link-collapse">Settings</span>
                    </a>
                </li>
            </ul>
        </div>
    </div>
</div>